name: Trigger on pull request and echo

on:
  pull_request:
    # Only on main
    branches:    
      - main    

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message to STDOUT
        run: "Will add code checks here in next challenge"
